apiVersion: v1
kind: Pod
metadata:
  name: miniwhoami-manual-pod2
  labels:
    hochschule: hbrs
    sem: ws22
spec:
  containers:
  - image: docker.fslab.de/tjonas2s/servmgmt-ws22/miniwhoami:latest
    name: miniwhoami
    ports:
    - containerPort: 80
      protocol: TCP
    imagePullPolicy: IfNotPresent
