version: '3.9'
services:
    miniwhoami-s1:
      container_name:  miniwhoami-s1
      image: docker.fslab.de/tjonas2s/servmgmt-ws22/miniwhoami
      networks:
        - loc_ipv6
      restart: unless-stopped

    miniwhoami-s2:
      container_name:  miniwhoami-s2
      image: docker.fslab.de/tjonas2s/servmgmt-ws22/miniwhoami
      networks:
        - loc_ipv6
      restart: unless-stopped

    miniwhoami-s3:
      container_name:  miniwhoami-s3
      image: docker.fslab.de/tjonas2s/servmgmt-ws22/miniwhoami
      networks:
        - loc_ipv6
      restart: unless-stopped

    loadbalancer:
      container_name: loadbalancer
      image: nginx:latest
      networks:
        my_ipv6:
          ipv6_address: 2001:638:408:200:ff38:cafe::9999
        loc_ipv6:
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      environment:
        - ENABLE_IPV6=true 
      restart: unless-stopped


networks:
  loc_ipv6:
    external: true      # Key-word for pre-existing network
  my_ipv6:
    external: true
